# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/ziti/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ziti)

$(call add-radio-file-sha1-checked,radio/abl.img,)
$(call add-radio-file-sha1-checked,radio/aop.img,)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,)
$(call add-radio-file-sha1-checked,radio/cpucp.img,)
$(call add-radio-file-sha1-checked,radio/devcfg.img,)
$(call add-radio-file-sha1-checked,radio/dsp.img,)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,)
$(call add-radio-file-sha1-checked,radio/featenabler.img,)
$(call add-radio-file-sha1-checked,radio/hyp.img,)
$(call add-radio-file-sha1-checked,radio/imagefv.img,)
$(call add-radio-file-sha1-checked,radio/keymaster.img,)
$(call add-radio-file-sha1-checked,radio/modem.img,)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,)
$(call add-radio-file-sha1-checked,radio/qupfw.img,)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,)
$(call add-radio-file-sha1-checked,radio/shrm.img,)
$(call add-radio-file-sha1-checked,radio/splash.img,)
$(call add-radio-file-sha1-checked,radio/tz.img,64c18d1756d4e69a5191cfa719207600e1df77e3)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,)
$(call add-radio-file-sha1-checked,radio/xbl.img,)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,)

endif
